
@host=https://localhost:7034
GET  {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NWFjYjg0NC0zMTY2LTQ2MGItOWZhMy0yMWM3MjEzMzU0ZjIiLCJqdGkiOiIyODQxNmU1ZS01NmJlLTQyNTAtODgxZS0xMmE2ZGI1MTdmMDYiLCJnaXZlbl9uYW1lIjoiQW5pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImV4cCI6MTY4Njc0NzQ4MywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.WxF6sN3HY8WSQUBJ6lNrnqE1tQ95v3SIuG47iyikSNw
